### ISSUE TITLE
TextEditor.getUri is deprecated.

### ISSUE THREAD

**Issue by LiteMorgan** [Azakur4/less-compiler#1]
Hi,

I had the following issue appear when trying to save a .less file and compile it. Using Atom version 0.190.0

Use `::getURI` instead

```
TextEditor.getUri (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2818:7)
LessCompilerProcess.compile (/Users/liam.morgan/.atom/packages/less-compiler/lib/less-compiler-process.coffee:18:24)
```

Any easy fix for this?

**Comment by Azakur4** [comment]
Yes, I will review this now, thanks for advice.

**Comment by Azakur4** [comment]
Solved in the new version.
